config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }
  resources :users, only: %I[index show] do
    resources :posts, only: %I[index show new create destroy]
  end

  root "users#index"

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create]
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:show, :index] do
          resources :comments, only: [:new, :create]
        end
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/partials/_post.html.erb
<article class ="posts">
  <h3 class="post-title">
  <%= link_to(post.title, user_post_path(id: post.id, user_id: post.user_id)) %>
  </h3>
<p><%= truncate(post.text, length: 250) %></p>
  <div class="post-infor">
    <p class="comments">Comments: <%=post.comments_counter %></p>
    <p class="likes">Likes: <%=post.likes_counter %></p>
   </div>
</article>

app/views/partials/_posts.html.erb
<article class ="posts">
  <h3 class="post-title">
  <%= link_to(post.title, user_post_path(id: post.id, user_id: post.author_id)) %>
  </h3>
<p><%= truncate(post.text, length: 250) %></p>
  <div class="post-infor">
    <p class="comments">Comments: <%=post.comments_counter %></p>
    <p class="likes">Likes: <%=post.likes_counter %></p>
   </div>
</article>

app/views/partials/_user.html.erb
<section class="user">
  <div class="img-div">
  </div>
  <div class="content">
    <h2><%= link_to(user.name, user_path(user)) %></h2>
    <p>
      Number of posts: <%= user.posts_counter %>
    </p>
  </div>
</section>