config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }
  resources :users, only: %I[index show] do
    resources :posts, only: %I[index show new create destroy]
  end

  root "users#index"

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create]
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:show, :index] do
          resources :comments, only: [:new, :create]
        end
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :comments, dependent: :destroy, class_name: 'Comment'
  has_many :likes, dependent: :destroy, class_name: 'Like'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :updates_post_counter

  def updates_post_counter
    user.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
    # load_and_authorize_resource
  
    def index
      user = User.find(params[:user_id])
      user_posts = Post.includes(:author, :comments, :likes).where(author_id: params[:user_id]).order(created_at: :desc)
      render json: user
      render json: user_posts
    end
  
    def show
      post = Post.find(params[:id])
      render json: post
    end
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @user_posts = Post.includes(:user, :comments, :likes).where(user_id: params[:user_id]).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
    @params = params
  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      redirect_to user_post_path(id: @post.id, user_id: @post.user_id), notice: 'Post created succesfully!'
    else
      render :new, alert: 'Post could not be created an Error occurred!'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    authorize! :destroy, @post
    @comment = @post.comments
    @comment.each(&:destroy)
    @post.destroy
    flash[:success] = ['Post Deleted Successfully']

    respond_to do |format|
      format.html { redirect_to "/users/#{current_user.id}/posts" }
      format.json { head :no_content }
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def index; end

  def show; end
end

app/views/posts/index.html.erb
<%= render partial:'partials/user', locals: {user: @user} %>

<% @user_posts.each do |post| %>
<%= render partial:'partials/post', locals: {post: post} %>
<ul class="comments-ul">
      <% post.recent_comments.each do |comment| %>
        <li><%= comment.user.name %>: <%= comment.text %>
      <% end %>
      </ul>
<% end %>

<%= link_to "Add Post", new_user_post_path(@user), class: "see-all-post-btn" %>

app/views/posts/new.html.erb
<%= form_with model: @post do |f| %>

    <% if @post.errors.any? %>
       <ul class ="errors-decr">
          <% @post.errors.full_messages.each do |errors| %>
            <li><%= errors %></li>
          <% end %>
       </ul>
    <% end %>
  <%= f.hidden_field :user_id, value: @params ? @params['user_id'] : '' %>
  <%= f.label :title, "Title:" %></br >
  <%= f.text_field :title, placeholder: "Article title" %>
  <%= f.label :text, "Article Description" %></br >
  <%= f.text_area :text, placeholder: "Write article here..." %></br >
  <%= f.submit "Submit post", disable_with: 'Submiting...' %>
<% end %>

app/views/posts/show.html.erb
<article class="post">
  <div class="owner-details">
  <h3 class="post-owner"><%= @post.title %>  by <%= @post.user.name %></h3>
  <div class="post-stats">
    <span>Comments: <%= @post.comments_counter %> &nbsp;,&nbsp;</span>
    <span>Likes: <%= @post.likes_counter %></span>
  </div>
  </div>
  <p><%= @post.text %></p>
</article>

<% if can? :destroy, @post %>
  <%= button_to "Delete", user_post_path(post_id: @post.id), method: :delete, data: {
    confirm: 'Are you sure you want to delete?'
  } %>
<% end %>
<br />
<%= form_for @like, url:post_likes_path(@post) do |f| %>
  <%= f.hidden_field :user_id, value: @post.user_id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.button nil, class: "like_btn" do %>
    Like<i class="fa-solid fa-thumbs-up"></i>
  <% end %>
  <% end %>

<ul class="comments-ul">
  <% @post.recent_comments.each do |comment| %>
    <li><%= comment.user.name %>: <%= comment.text %>
    <br>
    <% if can? :destroy, comment %>
      <%= button_to "Delete", post_comment_path(id: comment.id, post_id: @post.id), method: :delete, data: {
        confirm: 'Are you sure you want to delete?'
      } %>
    <% end %>
  <% end %>
</ul> 


<h5>Add comment</h5>
<%= form_for @comment, url:post_comments_path(@post) do |f| %>
  <%= f.hidden_field :user_id, value: @post.user.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.label :text %><br />
  <%= f.text_area :text, placeholder:'What are your thoughts on this post?' %><br />
  <%= f.submit "Submit comment", class:"see-all-post-btn", disable_with: 'Submiting Comment...' %>
<% end %>